Repository RP-StarHub/Back-end, pull requests merged in 2025-01, with the labels that each got.

#3 🐛 Fix: 엔티티 수정
  src/main/java/com/example/starhub/entity/ApplicantsEntity.java
  src/main/java/com/example/starhub/entity/LikeEntity.java
  src/main/java/com/example/starhub/entity/PostEntity.java
  src/main/java/com/example/starhub/entity/PostTechStackEntity.java
  src/main/java/com/example/starhub/entity/TechStackEntity.java
  src/main/java/com/example/starhub/entity/UserEntity.java
  src/main/java/com/example/starhub/entity/UserPostEntity.java
Labels: :bug: Fix

#4 [PR] ✨Feat: 이슈, pr 템플릿 내용 변경 모든 브렌치에 적용
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :sparkles: Feat

#7 [PR] ✨Feat: sign up
  build.gradle
  src/main/java/com/example/starhub/code/ResponseCode.java
  src/main/java/com/example/starhub/controller/UserController.java
  src/main/java/com/example/starhub/dto/request/CreateProfileRequestDto.java
  src/main/java/com/example/starhub/dto/request/CreateUserRequestDto.java
  src/main/java/com/example/starhub/dto/request/UsernameCheckRequestDto.java
  src/main/java/com/example/starhub/dto/response/ProfileResponseDto.java
  src/main/java/com/example/starhub/dto/response/UserResponseDto.java
  src/main/java/com/example/starhub/dto/response/UsernameCheckResponseDto.java
  src/main/java/com/example/starhub/entity/UserEntity.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/InvalidResponseCodeException.java
  src/main/java/com/example/starhub/exception/UserNotFoundException.java
  src/main/java/com/example/starhub/exception/UsernameAlreadyExistsException.java
  src/main/java/com/example/starhub/repository/UserRepository.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/response/dto/ErrorResponseDto.java
  src/main/java/com/example/starhub/response/dto/ResponseDto.java
  src/main/java/com/example/starhub/service/UserService.java
Labels: :sparkles: Feat, 📬 API

#8 [PR] ✨Feat: login
  build.gradle
  src/main/java/com/example/starhub/config/CorsMvcConfig.java
  src/main/java/com/example/starhub/config/RedisConfig.java
  src/main/java/com/example/starhub/config/SecurityConfig.java
  src/main/java/com/example/starhub/controller/UserController.java
  src/main/java/com/example/starhub/dto/response/UserResponseDto.java
  src/main/java/com/example/starhub/dto/response/UsernameCheckResponseDto.java
  src/main/java/com/example/starhub/dto/response/util/ResponseUtil.java
  src/main/java/com/example/starhub/dto/security/CustomUserDetails.java
  src/main/java/com/example/starhub/entity/UserEntity.java
  src/main/java/com/example/starhub/exception/BadRequestException.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/InvalidTokenCategoryException.java
  src/main/java/com/example/starhub/exception/InvalidTokenException.java
  src/main/java/com/example/starhub/exception/TokenExpiredException.java
  src/main/java/com/example/starhub/exception/TokenNotFoundInRedisException.java
  src/main/java/com/example/starhub/repository/UserRepository.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/service/CustomUserDetailsService.java
  src/main/java/com/example/starhub/service/RedisService.java
  src/main/java/com/example/starhub/service/UserService.java
  src/main/java/com/example/starhub/service/filter/JWTFilter.java
  src/main/java/com/example/starhub/service/filter/LoginFilter.java
  src/main/java/com/example/starhub/service/filter/LogoutFilter.java
  src/main/java/com/example/starhub/util/JWTUtil.java
Labels: :recycle: Refactor, :sparkles: Feat, 📬 API

#12 [PR] ✨Swagger 문서 작업
  build.gradle
  src/main/java/com/example/starhub/config/SecurityConfig.java
  src/main/java/com/example/starhub/config/swagger/LoginSwaggerConfig.java
  src/main/java/com/example/starhub/config/swagger/LogoutSwaggerConfig.java
  src/main/java/com/example/starhub/config/swagger/SwaggerConfig.java
  src/main/java/com/example/starhub/controller/UserController.java
  src/main/java/com/example/starhub/controller/docs/UserControllerDocs.java
  src/main/java/com/example/starhub/service/UserService.java
Labels: :sparkles: Feat

#13 [PR] ✨ Feat: post api
  src/main/java/com/example/starhub/controller/PostController.java
  src/main/java/com/example/starhub/controller/UserController.java
  src/main/java/com/example/starhub/controller/docs/PostControllerDocs.java
  src/main/java/com/example/starhub/dto/request/CreatePostRequestDto.java
  src/main/java/com/example/starhub/dto/request/PostUpdateRequestDto.java
  src/main/java/com/example/starhub/dto/response/CreatorDto.java
  src/main/java/com/example/starhub/dto/response/LikeDto.java
  src/main/java/com/example/starhub/dto/response/PostResponseDto.java
  src/main/java/com/example/starhub/dto/response/PostSummaryResponseDto.java
  src/main/java/com/example/starhub/entity/PostEntity.java
  src/main/java/com/example/starhub/entity/TechStackEntity.java
  src/main/java/com/example/starhub/entity/UserEntity.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/PostCreatorAuthorizationException.java
  src/main/java/com/example/starhub/exception/PostNotFoundException.java
  src/main/java/com/example/starhub/exception/UserProfileAlreadyExistsException.java
  src/main/java/com/example/starhub/repository/LikeRepository.java
  src/main/java/com/example/starhub/repository/PostRepository.java
  src/main/java/com/example/starhub/repository/PostTechStackRepository.java
  src/main/java/com/example/starhub/repository/TechStackRepository.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/service/PostService.java
  src/main/java/com/example/starhub/service/UserService.java
Labels: :sparkles: Feat, 📬 API

#15 [PR] ✨ Feat: 예외 처리 및 오류 코드 수정
  src/main/java/com/example/starhub/dto/request/CreateUserRequestDto.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/InvalidTokenMismatchException.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/service/UserService.java
  src/main/java/com/example/starhub/service/filter/JWTFilter.java
  src/main/java/com/example/starhub/service/filter/LoginFilter.java
  src/main/java/com/example/starhub/service/filter/LogoutFilter.java
Labels: :bug: Fix, :sparkles: Feat

#17 [PR] ✨ Feat: Implement AOP for Query Analysis
  src/main/java/com/example/starhub/performance/PerformanceConfig.java
  src/main/java/com/example/starhub/performance/PerformanceInterceptor.java
  src/main/java/com/example/starhub/performance/PerformanceMonitor.java
  src/main/java/com/example/starhub/performance/PerformanceMonitorAop.java
  src/main/java/com/example/starhub/performance/ProxyConnectionHandler.java
  src/main/java/com/example/starhub/performance/ProxyPreparedStatementHandler.java
Labels: :sparkles: Feat

#18 [PR] ✨Feat: 포스트 상세 가져오기 API 구현
  src/main/java/com/example/starhub/controller/PostController.java
  src/main/java/com/example/starhub/controller/docs/PostControllerDocs.java
  src/main/java/com/example/starhub/dto/response/LikeDto.java
  src/main/java/com/example/starhub/dto/response/PostDetailResponseDto.java
  src/main/java/com/example/starhub/dto/response/PostResponseDto.java
  src/main/java/com/example/starhub/dto/response/PostSummaryResponseDto.java
  src/main/java/com/example/starhub/dto/response/ProfileResponseDto.java
  src/main/java/com/example/starhub/dto/response/UserResponseDto.java
  src/main/java/com/example/starhub/dto/response/UsernameCheckResponseDto.java
  src/main/java/com/example/starhub/entity/UserPostEntity.java
  src/main/java/com/example/starhub/entity/enums/ApplicationStatus.java
  src/main/java/com/example/starhub/repository/ApplicantsRepository.java
  src/main/java/com/example/starhub/repository/LikeRepository.java
  src/main/java/com/example/starhub/repository/UserRepository.java
  src/main/java/com/example/starhub/service/PostService.java
  src/main/java/com/example/starhub/service/UserService.java
Labels: :sparkles: Feat, 📬 API

#20 [PR] ✨ Feat: 지원서관련 API
  src/main/java/com/example/starhub/controller/ApplicationController.java
  src/main/java/com/example/starhub/controller/PostController.java
  src/main/java/com/example/starhub/controller/docs/PostControllerDocs.java
  src/main/java/com/example/starhub/dto/request/ApplicationRequestDto.java
  src/main/java/com/example/starhub/dto/response/ApplicantDto.java
  src/main/java/com/example/starhub/dto/response/ApplicationResponseDto.java
  src/main/java/com/example/starhub/entity/ApplicantsEntity.java
  src/main/java/com/example/starhub/entity/ApplicationEntity.java
  src/main/java/com/example/starhub/exception/ApplicantAuthorizationException.java
  src/main/java/com/example/starhub/exception/ApplicationNotFoundException.java
  src/main/java/com/example/starhub/exception/CreatorAuthorizationException.java
  src/main/java/com/example/starhub/exception/DuplicateApplicationException.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/PostCreatorCannotApplyException.java
  src/main/java/com/example/starhub/exception/StudyConfirmedException.java
  src/main/java/com/example/starhub/repository/ApplicantsRepository.java
  src/main/java/com/example/starhub/repository/ApplicationRepository.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/service/ApplicationService.java
  src/main/java/com/example/starhub/service/PostService.java
Labels: :sparkles: Feat, 📬 API

#24 [PR] ♻ Refactor: 테이블명 수정
  src/main/java/com/example/starhub/controller/ApplicationController.java
  src/main/java/com/example/starhub/controller/MeetingController.java
  src/main/java/com/example/starhub/controller/PostController.java
  src/main/java/com/example/starhub/controller/docs/ApplicationControllerDocs.java
  src/main/java/com/example/starhub/controller/docs/MeetingControllerDocs.java
  src/main/java/com/example/starhub/controller/docs/PostControllerDocs.java
  src/main/java/com/example/starhub/dto/request/CreateMeetingRequestDto.java
  src/main/java/com/example/starhub/dto/request/MeetingUpdateRequestDto.java
  src/main/java/com/example/starhub/dto/response/LoginResponseDto.java
  src/main/java/com/example/starhub/dto/response/MeetingDetailResponseDto.java
  src/main/java/com/example/starhub/dto/response/MeetingResponseDto.java
  src/main/java/com/example/starhub/dto/response/MeetingSummaryResponseDto.java
  src/main/java/com/example/starhub/entity/ApplicationEntity.java
  src/main/java/com/example/starhub/entity/LikeEntity.java
  src/main/java/com/example/starhub/entity/MeetingEntity.java
  src/main/java/com/example/starhub/entity/MeetingTechStackEntity.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/MeetingCreatorCannotApplyException.java
  src/main/java/com/example/starhub/exception/MeetingNotFoundException.java
  src/main/java/com/example/starhub/repository/ApplicationRepository.java
  src/main/java/com/example/starhub/repository/LikeRepository.java
  src/main/java/com/example/starhub/repository/MeetingRepository.java
  src/main/java/com/example/starhub/repository/MeetingTechStackRepository.java
  src/main/java/com/example/starhub/repository/PostRepository.java
  src/main/java/com/example/starhub/repository/PostTechStackRepository.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/service/ApplicationService.java
  src/main/java/com/example/starhub/service/MeetingService.java
  src/main/java/com/example/starhub/service/PostService.java
  src/main/java/com/example/starhub/service/filter/LoginFilter.java
Labels: :recycle: Refactor

#26 [PR] ✨ Feat: 익명 사용자 경우 서비스 이용
  src/main/java/com/example/starhub/config/SecurityConfig.java
  src/main/java/com/example/starhub/controller/MeetingController.java
  src/main/java/com/example/starhub/dto/response/MeetingDetailResponseDto.java
  src/main/java/com/example/starhub/service/MeetingService.java
Labels: :sparkles: Feat

#27 ✨Feat: 모임원과 관련된 기능 구현
  src/main/java/com/example/starhub/controller/MeetingController.java
  src/main/java/com/example/starhub/dto/request/ConfirmMeetingRequestDto.java
  src/main/java/com/example/starhub/dto/response/ConfirmMeetingResponseDto.java
  src/main/java/com/example/starhub/dto/response/CreatorDto.java
  src/main/java/com/example/starhub/dto/response/MeetingResponseDto.java
  src/main/java/com/example/starhub/entity/ApplicationEntity.java
  src/main/java/com/example/starhub/entity/MeetingEntity.java
  src/main/java/com/example/starhub/entity/enums/ApplicationStatus.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/InvalidApplicationIdException.java
  src/main/java/com/example/starhub/exception/StudyNotConfirmedException.java
  src/main/java/com/example/starhub/repository/ApplicationRepository.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/service/ApplicationService.java
  src/main/java/com/example/starhub/service/MeetingService.java
Labels: :sparkles: Feat, 📬 API

#29 [PR] ✨ Feat: 기술 스택과 관련된 작업
  .gitignore
  src/main/java/com/example/starhub/config/SecurityConfig.java
  src/main/java/com/example/starhub/controller/MeetingController.java
  src/main/java/com/example/starhub/controller/TechStackController.java
  src/main/java/com/example/starhub/controller/UserController.java
  src/main/java/com/example/starhub/controller/docs/MeetingControllerDocs.java
  src/main/java/com/example/starhub/controller/docs/TechStackControllerDocs.java
  src/main/java/com/example/starhub/dto/request/CreateTechStackRequestDto.java
  src/main/java/com/example/starhub/dto/request/TechStackDto.java
  src/main/java/com/example/starhub/dto/response/TechStackResponseDto.java
  src/main/java/com/example/starhub/entity/TechStackEntity.java
  src/main/java/com/example/starhub/repository/TechStackRepository.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/service/MeetingService.java
  src/main/java/com/example/starhub/service/TechStackService.java
Labels: :sparkles: Feat, 📬 API

#31 [PR] 🐛 Fix: 지원서 관련 API 수정 및 쿼리 최적화
  src/main/java/com/example/starhub/controller/ApplicationController.java
  src/main/java/com/example/starhub/controller/docs/ApplicationControllerDocs.java
  src/main/java/com/example/starhub/dto/response/ApplicationResponseDto.java
  src/main/java/com/example/starhub/entity/ApplicationEntity.java
  src/main/java/com/example/starhub/repository/ApplicationRepository.java
  src/main/java/com/example/starhub/repository/MeetingRepository.java
  src/main/java/com/example/starhub/service/ApplicationService.java
Labels: :bug: Fix, 📬 API

#32 [PR] ✅ 지원서에 대한 테스트 케이스 추가
  .gitignore
  src/main/java/com/example/starhub/dto/request/ApplicationRequestDto.java
  src/test/java/com/example/starhub/service/ApplicationServiceTest.java
  src/test/resources/images/1234_profile.jpg
Labels: ✅ Test, 📬 API

#34 [PR] ✅Test: 기술 스택 기능에 대한 테스트 케이스 작성
  src/main/java/com/example/starhub/dto/request/TechStackDto.java
  src/test/java/com/example/starhub/service/TechStackServiceTest.java
Labels: ✅ Test

#36 [PR] ✨ Feat: 좋아요 관련 기능 구현
  src/main/java/com/example/starhub/controller/LikeController.java
  src/main/java/com/example/starhub/controller/docs/LikeControllerDocs.java
  src/main/java/com/example/starhub/entity/LikeEntity.java
  src/main/java/com/example/starhub/exception/GlobalExceptionHandler.java
  src/main/java/com/example/starhub/exception/LikeAlreadyExistsException.java
  src/main/java/com/example/starhub/exception/LikeNotFoundException.java
  src/main/java/com/example/starhub/repository/LikeRepository.java
  src/main/java/com/example/starhub/response/code/ErrorCode.java
  src/main/java/com/example/starhub/response/code/ResponseCode.java
  src/main/java/com/example/starhub/service/LikeService.java
  src/test/java/com/example/starhub/service/ApplicationServiceTest.java
  src/test/java/com/example/starhub/service/LikeServiceTest.java
Labels: :sparkles: Feat, ✅ Test, 📬 API

#37 [PR] 🐛 Fix: 모임 엔티티 및 응답 타입 수정
  src/main/java/com/example/starhub/dto/request/CreateMeetingRequestDto.java
  src/main/java/com/example/starhub/dto/request/MeetingUpdateRequestDto.java
  src/main/java/com/example/starhub/dto/response/MeetingResponseDto.java
  src/main/java/com/example/starhub/dto/response/MeetingSummaryResponseDto.java
  src/main/java/com/example/starhub/entity/MeetingEntity.java
Labels: :bug: Fix

#39 ✨Feat: 바뀐 요구사항에 맞게 비즈니스 로직 수정
  .gitignore
  src/main/java/com/example/starhub/admin/controller/AdminController.java
  src/main/java/com/example/starhub/admin/service/AdminService.java
  src/main/java/com/example/starhub/controller/MeetingController.java
  src/main/java/com/example/starhub/controller/TechStackController.java
  src/main/java/com/example/starhub/dto/response/LikeDto.java
  src/main/java/com/example/starhub/dto/response/MeetingDetailResponseDto.java
  src/main/java/com/example/starhub/dto/response/MeetingResponseDto.java
  src/main/java/com/example/starhub/entity/MeetingEntity.java
  src/main/java/com/example/starhub/entity/TechStackEntity.java
  src/main/java/com/example/starhub/repository/MeetingRepository.java
  src/main/java/com/example/starhub/repository/TechStackRepository.java
  src/main/java/com/example/starhub/service/MeetingService.java
  src/main/java/com/example/starhub/service/TechStackService.java
  src/test/java/com/example/starhub/admin/service/AdminServiceTest.java
  src/test/java/com/example/starhub/service/TechStackServiceTest.java
Labels: :bug: Fix, :recycle: Refactor, 📬 API

#40 [PR] 🐛Fix: 프로필 이미지 DTO에 추가하기
  src/main/java/com/example/starhub/dto/response/ApplicantDto.java
  src/main/java/com/example/starhub/dto/response/ApplicationResponseDto.java
  src/main/java/com/example/starhub/dto/response/ConfirmMeetingResponseDto.java
  src/main/java/com/example/starhub/dto/response/LoginResponseDto.java
  src/main/java/com/example/starhub/dto/response/MeetingResponseDto.java
  src/main/java/com/example/starhub/dto/response/ProfileResponseDto.java
  src/main/java/com/example/starhub/dto/security/CustomUserDetails.java
  src/main/java/com/example/starhub/service/filter/LoginFilter.java
Labels: :bug: Fix
